accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("user_update", views.user_update, name="user-update"),
    path("user_profile", views.user_profile, name="user-profile"),
    path("new_patient", views.new_patient, name="new-patient"),
    path("new_doctor", views.new_doctor, name="new-doctor"),
    path("new_staff", views.user_doctor_profile, name="user-doctor-profile"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("pages.urls")),
    path("docs/", include("docs.urls")),
    path("dogfoot/", include("dogfoot.urls")),
]

docs/urls.py
from django.urls import path
from . import views

app_name = "docs"
urlpatterns = [
    # path("", views.article_list, name="article-list"),
    # path("create/", views.article_create, name="article-create"),
    # path("<int:pk>", views.article_detail, name="article-detail"),
    # path("<int:pk>/update", views.article_update, name="article-update"),
    # path("<int:pk>/delete", views.article_delete, name="article-delete"),
    path("", views.book_list, name="book-list"),
    path("layout/", views.layout, name="layout"),
    path("book/create/", views.book_create, name="book-create"),
    path("book/<int:pk>/", views.book_detail, name="book-detail"),
    path("book/<int:pk>/update", views.book_update, name="book-edit"),
    path("book/<int:pk>/delete", views.book_delete, name="book-delete"),
    path("article/", views.book_delete, name="article-list"),
    path("article/create/", views.article_create, name="article-create"),
    path("article/<int:pk>/", views.article_detail, name="article-detail"),
    path("article/<int:pk>/update", views.article_update, name="article-edit"),
    path("article/<int:pk>/delete", views.article_delete, name="article-delete"),
]

dogfoot/urls.py
from django.urls import path, include
from . import views

app_name = "dogfoot"
urlpatterns = [
    path("", views.home, name="home"),
    path("table/<str:app_name>", views.get_tables, name="get-tables"),
    path(
        "table/<str:app_name>/<str:model_name>/generate",
        views.dj_code_generate,
        name="generate",
    ),
    path(
        "table/<str:app_name>/<str:model_name>/get_recent_records",
        views.get_recent_records,
        name="get-recent-records",
    ),
    path(
        "get_db_schema/",
        views.get_db_schema,
        name="get-db-schema",
    ),
]
# Compare this snippet from dogfoot/models.py:

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base copy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
	<title>{% block title %}DjangoX{% endblock title %}</title>
	<meta name="description" content="A framework for launching new Django projects quickly.">
	<meta name="author" content="">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

	{% block css %}
	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
		integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
		crossorigin="anonymous"></script>

	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	{% endblock %}
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		{% include '_nav.html' %}

	</nav>

	<div class="container">
		{% include '_messages.html' %}

		{% block content %}

		{% endblock content %}
	</div>

	<footer class="footer">
		<div class="container">
			<span class="text-muted">Footer...</span>
		</div>
	</footer>

	{% block javascript %}
	<!-- Bootstrap JavaScript -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
		crossorigin="anonymous"></script>

	<!-- Project JS -->
	<script src="{% static 'js/base.js' %}"></script>

	{% endblock javascript %}

</body>

</html>

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
	<title>{% block title %}DjangoX{% endblock title %}</title>
	<meta name="description" content="A framework for launching new Django projects quickly.">
	<meta name="author" content="">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

	{% block css %}
	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">



	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	{% endblock %}
</head>

<body>
	<div class="container">

		<header class="p-3 mb-3 border-bottom ">
			<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
				<a href="/"
					class="d-flex align-items-center justify-content-start mb-2 mb-lg-0 link-body-emphasis text-decoration-none"
					style="margin-right: 4rem;">

					<h4>ImplantSavvy</h4>
				</a>

				<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
					<li><a href="#" class="nav-link px-2 link-secondary">How it works</a></li>
					<li><a href="#" class="nav-link px-2 link-body-emphasis">Smile Story</a></li>
					<li>
						<a href="{% url 'docs:article-list' %}" class="nav-link px-2 link-body-emphasis">Docs</a>
					</li>
				</ul>
				<div class="dropdown text-end">
					<ul class="nav col-9 col-lg-auto me-lg-auto mb-2 justify-content-end mb-md-0">
						{% if user.is_authenticated %}

						{% if user.is_staff %}
						<li class="nav-item">
							<a class="btn button " href="#">Dashboard</a>
						</li>
						<li class="nav-item">
							<a class="btn button " href="{% url 'dogfoot:home' %}">Dogfoot</a>
						</li>
						{% else %}
						<li class="nav-item">
							<a class="btn button " href="#">Dashboard</a>
						</li>
						{% endif %}
						<li class="nav-item">
							<a class="btn button " href="{% url 'account_login' %}">Log out</a>
						</li>

						{% else %}
						<li class="nav-item">
							<a class="btn button " href="{% url 'account_login' %}">Log in</a>
						</li>
						<li class="nav-item">
							<a class="btn button " href="{% url 'account_signup' %}">Sign Up</a>
						</li>


						{% endif %}



					</ul>
				</div>


			</div>


		</header>
	</div>
	<div class="container">
		{% include '_messages.html' %}

		{% block content %}

		{% endblock content %}
	</div>

	<footer class="py-3 my-4" style="border-top:1px solid;">
		<ul class="nav justify-content-center border-bottom pb-3 mb-3">
			<li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
			<li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
			<li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
			<li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
			<li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
		</ul>
		<p class="text-center text-body-secondary">© 2023 Company, Inc</p>
	</footer>

	{% block javascript %}
	<!-- Bootstrap JavaScript -->

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
		integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
		crossorigin="anonymous"></script>

	<!-- Project JS -->
	<script src="{% static 'js/base.js' %}"></script>

	{% endblock javascript %}

</body>

</html>

templates/_messages.html
{% if messages %}
<div class="row">
    <div class="col-md-12">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

templates/_nav.html
<div class="container">
    <a class="navbar-brand h1" href="/">ImplantSavvy</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07"
        aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExample07"></div>
    {% if user.is_authenticated %}

    {% if user.profile.category == 'Patent' %}


    <ul class="navbar-nav ms-5 me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">How it works</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">For Patients</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:home' %}">Dashboard {{ user.profile.category }}</a>
        </li>
    </ul>

    <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Hello
                {{ user.username }}</a>

            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'accounts:user-profile' %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'accounts:user-update' %}">Basic</a></li>
                <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a></li>
                <li><a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a></li>
            </ul>
        </li>
    </ul>

    {% else %}

    <ul class="navbar-nav ms-5 me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">How it works</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:home' %}">Dashboard {{ user.profile.category }}</a>
        </li>
    </ul>

    <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Hello
                {{ user.username }}</a>

            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'accounts:user-doctor-profile' %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'accounts:user-update' %}">Basic</a></li>
                <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a></li>
                <li><a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a></li>
            </ul>
        </li>
    </ul>

    {% endif %}

</div>

{% else %}

<ul class="navbar-nav ms-5 me-auto mb-2 mb-lg-0">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">How it works</a>
    </li>
    <li class="nav-item">
        a class="nav-link" href="#">For Patients</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'icases:icase-list' %}">Dashboard {{ user.profile.category }}</a>
    </li>
</ul>

<ul class="navbar-nav mb-2 mb-lg-0">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'account_login' %}">Log in</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'account_signup' %}">Sign Up</a>
    </li>
</ul>

{% endif %}
</div>

</div>