accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("user_update", views.user_update, name="user-update"),
    path("user_profile", views.user_profile, name="user-profile"),
    path("new_patient", views.new_patient, name="new-patient"),
    path("new_doctor", views.new_doctor, name="new-doctor"),
    path("new_staff", views.user_doctor_profile, name="user-doctor-profile"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("pages.urls")),
    path("docs/", include("docs.urls")),
    path("dogfoot/", include("dogfoot.urls")),
]

docs/urls.py
from django.urls import path
from . import views

app_name = "docs"
urlpatterns = [
    # path("", views.article_list, name="article-list"),
    # path("create/", views.article_create, name="article-create"),
    # path("<int:pk>", views.article_detail, name="article-detail"),
    # path("<int:pk>/update", views.article_update, name="article-update"),
    # path("<int:pk>/delete", views.article_delete, name="article-delete"),
    path("", views.book_list, name="book-list"),
    path("layout/", views.layout, name="layout"),
    path("book/create/", views.book_create, name="book-create"),
    path("book/<int:pk>/", views.book_detail, name="book-detail"),
    path("book/<int:pk>/update", views.book_update, name="book-edit"),
    path("book/<int:pk>/delete", views.book_delete, name="book-delete"),
    path("article/", views.book_delete, name="article-list"),
    path("article/create/", views.article_create, name="article-create"),
    path("article/<int:pk>/", views.article_detail, name="article-detail"),
    path("article/<int:pk>/update", views.article_update, name="article-edit"),
    path("article/<int:pk>/delete", views.article_delete, name="article-delete"),
]

docs/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from accounts.models import CustomUser


class Book(models.Model):
    user = models.ForeignKey("accounts.CustomUser", on_delete=models.CASCADE)
    title = models.CharField(max_length=255, blank=False, null=False)
    author = models.CharField(max_length=255, null=True, blank=True)
    cover = models.ImageField(upload_to="covers/", blank=True)
    description = models.TextField()
    product_name = models.CharField(max_length=255, blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    user = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, blank=True, null=True
    )
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, blank=True, null=True)
    subject = models.CharField(max_length=100)
    sub_text = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField()
    ordery = models.IntegerField(default=0)
    orderx = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse("support:article-detail", kwargs={"pk": self.pk})

docs/forms.py
from django import forms
from .models import Article, Book


class ArticleForm(forms.ModelForm):

    subject = forms.TextInput()
    sub_text = forms.TextInput
    description = forms.CharField(widget=forms.Textarea)
    available = forms.BooleanField()

    class Meta:
        model = Article
        fields = "__all__"


class bookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"


# class ArticleForm(forms.Form):

#     subject = forms.CharField()
#     sub_text = forms.CharField()
#     description = forms.CharField(widget=forms.Textarea)
#     available = forms.BooleanField()

#     class Meta:
#         model = Article
#         fields = {
#             "subject",
#             "sub_text",
#             "description",
#             "available",
#         }

docs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Book as book
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import ArticleForm
from django.utils import timezone


def layout(request):
    return render(request, "docs/layout.html")


def book_list(request):
    books = Book.objects.all()
    paginator = Paginator(books, 10)
    page = request.GET.get("page")
    books = paginator.get_page(page)
    page_obj = paginator.get_page(page)
    context = {
        "app_name": app_name,
        "nav_list": nav_list,
        "side_list": side_list,
        "breadcrumb": breadcrumb,
        "title": title,
        "books": books,
        "model1_list": model1_list,
        "model2_list": model2_list,
    }
    return render(request, "docs/book_list.html", context)


def book_detail(request, pk):
    book = Book.objects.get_object_or_404(pk=pk)
    model1_list = model1.objects.all()
    context = {
        "app_name": app_name,
        "nav_list": nav_list,
        "side_list": side_list,
        "breadcrumb": breadcrumb,
        "title": title,
        "books": books,
        "model1_list": model1_list,
        "user": request.user,
    }
    return render(request, "docs/book_detail.html", context)


def book_create(request):
    context = {
        "app_name": app_name,
        "nav_list": nav_list,
        "side_list": side_list,
        "breadcrumb": breadcrumb,
        "title": title,
        "model1_list": model1_list,
        "user": request.user,
    }
    if request.method == "POST":
        form = bookForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            user = request.user
            form.save()
            return redirect("docs:book-list")
    else:
        form = bookForm()
    context["form"] = form
    return render(request, "docs/book_create.html", {"form": form})


def book_update(request, pk):
    context = {
        "app_name": app_name,
        "nav_list": nav_list,
        "side_list": side_list,
        "breadcrumb": breadcrumb,
        "title": title,
        "model1_list": model1_list,
        "user": request.user,
    }
    if request.method == "POST":
        book = Book.objects.get_object_or_404(pk=pk)
        form = bookForm(request.POST, instance=book)
        if form.is_valid():
            form = form.save(commit=False)
            updated_at = timezone.now()
            form.save()
            return redirect("docs:book-list")
    else:
        book = Book.get_object_or_404(pk=pk)
        form = bookForm(instance=book)
    context["form"] = form
    return render(request, "docs/book_edit.html", context)


def book_delete(request, pk):
    book = Book.objects.get_object_or_404(pk=pk)
    book.delete()
    return redirect("docs:book-list")


def article_list(request):
    articles = Article.objects.all().order_by("-created_at")
    paginator = Paginator(articles, 10)
    page = request.GET.get("page")
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    return render(request, "docs/article_list.html", {"page_obj": articles})


def article_detail(request, pk):
    article = Article.objects.get(pk=pk)
    return render(request, "docs/article_detail.html", {"article": article})


def article_create(request):
    form = ArticleForm()
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            user = request.user
            form.save()
            return redirect("docs:article-list")
    else:
        form = ArticleForm()
    return render(request, "docs/article_create.html", {"form": form})


def article_update(request, pk):
    article = Article.objects.get(pk=pk)
    form = ArticleForm(instance=article)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form = form.save(commit=False)
            user = request.user
            form.save()
            return redirect("docs:article-list")
    else:
        form = ArticleForm(instance=article)
        article_id = article.id

    return render(
        request, "docs/article_update.html", {"form": form, "article_id": article_id}
    )


def article_delete(request, pk):
    doc = Article.objects.get(pk=pk)
    doc.delete()
    return redirect("docs:article-list")

templates/docs/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <title>{% block title %}Conebeam Center Dashboard{% endblock title %}</title>
    <meta name="description" content="A framework for launching new Django projects quickly.">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <script src="https://unpkg.com/@popperjs/core@2"></script>

    {% block css %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/doc_sidebar.css' %}">

    {% endblock %}


</head>

<body>
    <div class="container-fluid">
        <header class="p-3 mb-3 border-bottom ">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/"
                    class="d-flex align-items-center justify-content-start mb-2 mb-lg-0 link-body-emphasis text-decoration-none"
                    style="margin-right: 4rem;">

                    <h4>Primrose </h4>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="/" class="nav-link px-2 link-body-emphasis">Homepage</a></li>
                    <li><a href="{% url 'docs:article-list' %}" class="nav-link px-2 link-body-emphasis">Articles</a>
                    </li>
                </ul>

                <div class="dropdown text-end">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Hello
                        {{ user.username }}</a>
                    </a>
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url 'accounts:user-profile' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:user-update' %}">Basic user information</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a></li>
                    </ul>
                </div>
            </div>
        </header>
    </div>


    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">

                <ul class="list-unstyled ps-0">
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                            data-bs-target="#home-collapse" aria-expanded="true">
                            By product
                        </button>
                        <div class="collapse show" id="home-collapse">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">

                            </ul>
                        </div>
                    </li>
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                            data-bs-target="#dashboard-collapse" aria-expanded="false">
                            By Manual name
                        </button>
                        <div class="collapse show" id="dashboard-collapse">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                {% for manual in manual_list %}
                                <li><a href="#" class="link-dark rounded">
                                        {{ manual.title }}</a></li>
                                {% endfor %}

                            </ul>
                        </div>
                    </li>

                </ul>
            </div>
            <div class="col-md-10">

                {% block content %}

                {% endblock content %}

                {% block right_side_content %}

                {% endblock right_side_content %}


            </div>
        </div>
        <footer class="py-3 my-4" style="border-top:1px solid;">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
            </ul>
            <p class="text-center text-body-secondary">© 2023 Primrose William, Inc</p>
        </footer>

    </div>


    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.js"
        integrity="sha384-eI7PSr3L1XLISH8JdDII5YN/njoSsxfbrkCTnJrzXt+ENP5MOVBxD+l6sEG4zoLp"
        crossorigin="anonymous"></script>

</body>

</html>

templates/docs/article_create.html
{% extends "docs/_base.html" %}
{% load crispy_forms_tags %}


{% block title %}Create new article {% endblock %}

{% block content %}
<main class="d-flex flex-column p-2 mb-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <h4 class="h2">New article </h4>
        </div>
        <hr>
        <div class="p-2">
            <a class="btn btn-primary" href="{% url 'docs:article-list'%}">Home</a>

        </div>
    </div>
    <hr>
    <div class="p-2 ">
        <div class="row g-5">
            <div class="col-md-9">
                <article class="blog-post">

                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy}}
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </article>
            </div>
            <div class="col-md-4">

            </div>
        </div>
    </div>
</main>
{% endblock %}
```

templates/docs/article_create_btw.html
{% extends "support/_base.html" %}
{% load crispy_forms_tags %}


{% block title %}Create new article {% endblock %}

{% block content %}
<main class="d-flex flex-column p-2 mb-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <h4 class="h2">New article of {{ manual.title }}</h4>
        </div>
        <hr>
        <div class="p-2">
            <a class="btn btn-primary" href="{% url 'support:home'%}">Home</a>
            <a class="btn btn-primary" href="{% url 'support:manual-detail' manual.id %}">
                Back to Manual ({{manual.title }})
            </a>

            <!-- <a class="btn btn-primary" href="{% url 'icases:icase-list' %}">List</a> -->
        </div>
    </div>
    <hr>
    <div class="p-2 ">
        <div class="row g-5">
            <div class="col-md-8">
                <article class="blog-post">

                    <form method="post">
                        {% csrf_token %}
                        {{ form | crispy}}
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </article>
            </div>
            <div class="col-md-4">

            </div>
        </div>
    </div>
</main>
{% endblock %}
```

templates/docs/article_delete.html
{% extends "support/_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<main class="d-flex flex-column p-2 mb-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <h4 class="h2">Article Delete of {{ manual.title }}</h4>
        </div>
        <hr>
        <div class="p-2">

            <a class="btn btn-info" href="{% url 'support:article-update' manual.id article.id %}">Edit this article</a>
            <a class="btn btn-primary" href="{% url 'support:home'%}">Manual home</a>
            <a class="btn btn-primary" href="{% url 'support:manual-detail' manual.id %}">
                Back to Manual ({{manual.title }})
            </a>
            <a class="btn btn-danger" href="{% url 'support:article-delete' manual.id article.id %}">Delete</a>
        </div>
    </div>
    <hr>
    <div class="p-2 ">
        <div class="row g-5">
            <div class="col-md-8">
                <article class="blog-post">
                    <h2 class="display-5 link-body-emphasis mb-1">{{ article.subject }}</h2>
                    <p class="blog-post-meta">{{ article.created_at }}</p>
                    <small class="text-body-secondary">by {{ article.user.username }}</small>

                    <p>{{ article.description }}</p>

                </article>
                <div>
                    <form method="post">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
</main>
{% endblock %}
```

templates/docs/article_detail.html
{% extends "docs/_base.html" %}

{% load markdown_filter %}

{% block content %}
<main class="d-flex flex-column p-2 mb-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <h4 class="h2">Article detail</h4>
        </div>
        <hr>
        <div class="p-2">

            <a class="btn btn-info" href="{% url 'docs:article-update' article.id %}">Edit this article</a>
            <a class="btn btn-primary" href="{% url 'docs:article-list'%}">Manual home</a>
            <a class="btn btn-primary" href="{% url 'docs:article-detail' article.id %}">
                Back to Manual ({{article.title }})
            </a>
            <a class="btn btn-danger" href="{% url 'docs:article-delete' article.id %}">Delete</a>
        </div>
    </div>
    <hr>
    <div class="p-2 ">
        <div class="row g-5">
            <div class="col-md-8">
                <article class="blog-post py-4">
                    <div class="d-flex flex-row justify-content-between mb-2">

                        <div class="h4">{{ article.subject }}</div>

                        <div>
                            <div class="d-flex d-flex-row">

                                <div class="d-flex d-flex-row" style="margin-right:4px;">
                                    <input id="url" class="form-control form-control-sm" readonly style="height:14px;"
                                        value="{{ request.build_absolute_uri}}{{ article.id }}">
                                    <button class="btn btn-secondary btn-sm" onclick="CopySingle()"
                                        id="copybtn">Copy</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <p>{{ article.description|convert_markdown|safe }}</p>

                </article>

            </div>

        </div>
    </div>

</main>
<script>
    function CopySingle() {
        // Get the text field
        var copyText = document.getElementById("url");

        // Select the text field
        copyText.select();
        copyText.setSelectionRange(0, 99999); // For mobile devices

        // Copy the text inside the text field
        navigator.clipboard.writeText(copyText.value)
            .then(function () {
                // Alert the copied text
                // alert("Copied the text: " + copyText.value);
                document.getElementById("copybtn").innerHTML = "Copied";
            })
            .catch(function (error) {
                console.error('Could not copy text: ', error);
            });
    }
</script>
{% endblock %}

templates/docs/article_update.html
{% extends "docs/_base.html" %}

{% load crispy_forms_tags %}


{% block title %}Update article {% endblock %}

{% block content %}
<main class="d-flex flex-column p-2 mb-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <h4 class="h2">Edit article of {{ manual.title }}</h4>
        </div>
        <hr>
        <div class="p-2">
            <a class="btn btn-primary" href="{% url 'docs:article-list'%}">Home</a>
            <a class="btn btn-primary" href="{% url 'docs:article-detail' article_id %}">Detail</a>

        </div>
    </div>
    <hr>
    <div class="p-2 ">
        <div class="row g-5">
            <div class="col-md-8">
                <article class="blog-post">

                    <form method="post">
                        {% csrf_token %}
                        {{ form | crispy}}
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </article>
            </div>
            <div class="col-md-4">

            </div>
        </div>
    </div>
</main>
{% endblock %}
```

templates/docs/manual_detail.html
{% extends "support/_base.html" %}
{% load markdown_filter %}

{% block content %}
<main class="d-flex flex-column p-2 mb-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <article class="blog-post">
                <h2 class="display-6 link-body-emphasis mb-1">{{ manual.title }}</h2>
                <p class="blog-post-meta">{{ manual.created_at }}</p>
                <small class="text-body-secondary">by {{ manual.user.username }}</small>
                <p>{{ manual.description | render_markdown }}</p>
            </article>
        </div>
        <hr>
        <div class="p-2">
            <a class="btn btn-primary" href="{% url 'support:home' %}">Home</a>
            <a class="btn btn-primary" href="{% url 'support:article-create' manual.id %}">New article</a>
            <a class="btn btn-primary" href="{% url 'support:manual-reorder' manual.id %}">Re-Ordering</a>
            <!-- <a class="btn btn-primary" href="{% url 'icases:icase-list' %}">List</a> -->
        </div>
    </div>
    <hr>
    <div class="p-2 ">
        <div class="row g-5">
            <div class="col-md-8 row-gap-3">

                {% for article in article_list %}
                <div class="mb-3 ">
                    {% if article.orderx == 0 %}
                    <div class="h4">
                        {% elif article.orderx == 1 %}

                        <div class="h5 ">
                            {% endif %}
                            {{ article.subject }} ({{ article.ordery }}/{{ article.orderx }})
                            <a class="btn btn-light btn-sm"
                                href="{% url 'support:article-update' manual.id article.id %}">
                                Edit
                            </a>
                            <a class="btn btn-light btn-sm"
                                href="{% url 'support:article-create-btw' manual.id article.id article.ordery article.orderx %}">
                                Insert an article above..
                            </a>
                        </div>
                        <div>
                            <p>{{ article.description | render_markdown }}</p>
                        </div>
                        <div class="">
                            <br>

                        </div>

                    </div>

                    {% empty %}
                    <div>No records</div>

                    {% endfor %}

                </div>
                <div class="col-md-4">
                    <p class="fs-6">Table of Content</p>
                    <ul class="list-group">

                        {% for article in article_list %}
                        {% if article.orderx == 0 %}
                        <li class="unsytle fs-6">{{ article.subject }}</li>
                        {% elif article.orderx == 1 %}
                        <ul>
                            <li>{{ article.subject }}</li>
                        </ul>

                        {% endif %}



                        {% endfor %}

                    </ul>

                </div>

            </div>
        </div>

</main>
{% endblock %}
```

templates/docs/manual_form.html
{% extends 'support/_base.html' %}
{% load crispy_forms_tags %}


{% block title %}Update manual {% endblock %}

{% block content %}
<main class="d-flex flex-column p-2">
    <div class="d-flex justify-content-between" style="border-bottom: solid 1px;">
        <div class="p-2">
            <h4 class="h2">Edit case</h4>
        </div>
        <div class="p-2">
            <a class="btn btn-primary" href="{% url 'icases:icase-list' %}">Back to case list</a>
        </div>
    </div>
    <hr>
    <div class="p-2 ">
        <div class="" style="width:750px;">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <input class="btn btn-primary" type="submit" value="Submit">
            </form>
        </div>
    </div>
</main>
{% endblock content %}

templates/docs/phot_delete.html
{% extends "support/_base.html" %}

{% block content %}
<main class="d-flex flex-column p-2 mb-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <h4 class="h2">Photo gallery</h4>
        </div>
        <hr>
        <div class="p-2">
            <a class="btn btn-primary" href="{% url 'support:photo-create' %}">Add new photo</a>
            <!-- <a class="btn btn-primary" href="{% url 'icases:icase-list' %}">List</a> -->
        </div>
    </div>
    <hr>
    <hr>
    <div class="p-2 ">
        <div class="row g-5">
            <div class="col-md-8 row-gap-3">



            </div>
            <div class="col-md-4">


            </div>

        </div>
    </div>

</main>
{% endblock %}

templates/docs/photo_create.html
{% extends "support/_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<main class="d-flex flex-column p-2 mb-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <h4 class="h2">Photo gallery</h4>
        </div>
        <hr>
        <div class="p-2">
            <a class="btn btn-primary" href="{% url 'support:photo-create' %}">Add new photo</a>
            <!-- <a class="btn btn-primary" href="{% url 'icases:icase-list' %}">List</a> -->
        </div>
    </div>
    <hr>
    <hr>
    <div class="p-2 ">
        <div class="row g-5">
            <div class="col-md-8 row-gap-3">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy}}
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
            </div>
            <div class="col-md-4">


            </div>

        </div>
    </div>

</main>
{% endblock %}

templates/docs/photo_detail.html
{% extends "support/_base.html" %}

{% block content %}
<main class="d-flex flex-column p-2 mb-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <h4 class="h2">Photo gallery</h4>
        </div>
        <hr>
        <div class="p-2">
            <a class="btn btn-primary" href="{% url 'support:photo-create' %}">Add new photo</a>
            <!-- <a class="btn btn-primary" href="{% url 'icases:icase-list' %}">List</a> -->
        </div>
    </div>
    <hr>
    <hr>
    <div class="p-2 ">
        <div class="row g-5">
            <div class="col-md-8 row-gap-3">



            </div>
            <div class="col-md-4">


            </div>

        </div>
    </div>

</main>
{% endblock %}

templates/docs/photo_list.html
{% extends "support/_base.html" %}

{% block content %}
<style>
    .image-thumbail {
        height: 200px;
        object-fit: cover;
    }

    .list-group-item a {
        text-decoration: none;
        color: black;
    }
</style>

<main class="d-flex flex-column p-2 mb-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <h4 class="h2">Photo gallery</h4>
        </div>
        <hr>
        <div class="p-2">
            <a class="btn btn-primary" href="{% url 'support:photo-create' %}">Add new photo</a>
            <!-- <a class="btn btn-primary" href="{% url 'icases:icase-list' %}">List</a> -->
        </div>
    </div>
    <hr>
    <div class="p-2 ">
        <div class="row g-5">
            <div class="col-md-8 row-gap-3">

                {% for photo in photos %}
                <div class="col-md-4">
                    <div class="card my-2">
                        <img class="image-thumbail" src="{{photo.image.url}}" alt="Card image cap">


                        <a href="#" class="btn btn-outline-dark btn-sm m-1">View</a>
                        <p class="m-1">{{photo.name}}</p>
                        <p class="m-1">{{photo.tags}}</p>
                        <p class="m-1">http://127.0.0.1:8000/{{photo.image.url}}</p>

                    </div>

                </div>
                {% empty %}
                <h3>No photos...</h3>
                {% endfor %}


            </div>
            <div class="col-md-4">


            </div>

        </div>
    </div>

</main>
{% endblock %}

templates/docs/photo_update.html
{% extends "support/_base.html" %}

{% block content %}
<main class="d-flex flex-column p-2 mb-3">
    <div class="d-flex justify-content-between">
        <div class="p-2">
            <h4 class="h2">Photo gallery</h4>
        </div>
        <hr>
        <div class="p-2">
            <a class="btn btn-primary" href="{% url 'support:photo-create' %}">Add new photo</a>
            <!-- <a class="btn btn-primary" href="{% url 'icases:icase-list' %}">List</a> -->
        </div>
    </div>
    <hr>
    <hr>
    <div class="p-2 ">
        <div class="row g-5">
            <div class="col-md-8 row-gap-3">



            </div>
            <div class="col-md-4">


            </div>

        </div>
    </div>

</main>
{% endblock %}