accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path("user_update", views.user_update, name="user-update"),
    path("user_profile", views.user_profile, name="user-profile"),
    path("new_patient", views.new_patient, name="new-patient"),
    path("new_doctor", views.new_doctor, name="new-doctor"),
    path("new_staff", views.user_doctor_profile, name="user-doctor-profile"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/", include("accounts.urls")),
    path("", include("pages.urls")),
    path("docs/", include("docs.urls")),
    path("dogfoot/", include("dogfoot.urls")),
]

docs/urls.py
from django.urls import path
from . import views

app_name = "docs"
urlpatterns = [
    # path("", views.article_list, name="article-list"),
    # path("create/", views.article_create, name="article-create"),
    # path("<int:pk>", views.article_detail, name="article-detail"),
    # path("<int:pk>/update", views.article_update, name="article-update"),
    # path("<int:pk>/delete", views.article_delete, name="article-delete"),
    path("", views.book_list, name="book-list"),
    path("layout/", views.layout, name="layout"),
    path("book/create/", views.book_create, name="book-create"),
    path("book/<int:pk>/", views.book_detail, name="book-detail"),
    path("book/<int:pk>/update", views.book_update, name="book-edit"),
    path("book/<int:pk>/delete", views.book_delete, name="book-delete"),
    path("article/", views.book_delete, name="article-list"),
    path("article/create/", views.article_create, name="article-create"),
    path("article/<int:pk>/", views.article_detail, name="article-detail"),
    path("article/<int:pk>/update", views.article_update, name="article-edit"),
    path("article/<int:pk>/delete", views.article_delete, name="article-delete"),
]

dogfoot/urls.py
from django.urls import path, include
from . import views

app_name = "dogfoot"
urlpatterns = [
    path("", views.home, name="home"),
    path("table/<str:app_name>", views.get_tables, name="get-tables"),
    path(
        "table/<str:app_name>/<str:model_name>/generate",
        views.dj_code_generate,
        name="generate",
    ),
    path(
        "table/<str:app_name>/<str:model_name>/get_recent_records",
        views.get_recent_records,
        name="get-recent-records",
    ),
    path(
        "get_db_schema/",
        views.get_db_schema,
        name="get-db-schema",
    ),
]
# Compare this snippet from dogfoot/models.py:

dogfoot/models.py
from django.db import models

# Create your models here.

dogfoot/views.py
from django.apps import apps
from django.db import connection
from django.db.models import ForeignKey
from django.shortcuts import render
import json
import datetime

from .utils import get_app_names, get_dj_code_generate


def datetime_handler(x):
    if isinstance(x, datetime.datetime):
        return x.isoformat()
    raise TypeError("Unknown type")


def home(request):

    app_names = get_app_names()
    return render(request, "dogfoot/index.html", {"app_names": app_names})


def get_tables(request, app_name):
    app_names = get_app_names()

    with connection.cursor() as cursor:
        all_table_names = connection.introspection.table_names()
        if app_name == "all":
            app_table_names = all_table_names
        else:
            app_table_names = [
                name for name in all_table_names if name.startswith(app_name + "_")
            ]
        table_columns = {
            table: connection.introspection.get_table_description(cursor, table)
            for table in app_table_names
        }

    return render(
        request,
        "dogfoot/table.html",
        {
            "table_columns": table_columns,
            "app_name": app_name,
            "app_names": app_names,
        },
    )


def dj_code_generate(request, app_name, model_name):
    """
    Generates Django code for a given app and model.

    Parameters:
    - request: The incoming HTTP request.
    - app_name: The name of the Django app.
    - model_name: The name of the model in the app.

    Returns:
    - A rendered HTML page with the generated code and table descriptions.
    """

    app_names = get_app_names()
    code_gen = get_dj_code_generate(app_name, model_name)

    if not code_gen:
        code_gen = "No code generated"

    with connection.cursor() as cursor:
        all_table_names = connection.introspection.table_names()
        app_table_names = [
            name for name in all_table_names if name.startswith(app_name + "_")
        ]
        table_columns = {
            table: connection.introspection.get_table_description(cursor, table)
            for table in app_table_names
        }

    return render(
        request,
        "dogfoot/dj_code_generate.html",
        {
            "app_name": app_name,
            "model_name": model_name,
            "app_names": app_names,
            "code_gen": code_gen,
            "table_columns": table_columns,
        },
    )


def get_recent_records(request, app_name, model_name):

    app_names = get_app_names()

    with connection.cursor() as cursor:
        all_table_names = connection.introspection.table_names()
        app_table_names = [
            name for name in all_table_names if name.startswith(app_name + "_")
        ]
        table_columns = {
            table: connection.introspection.get_table_description(cursor, table)
            for table in app_table_names
        }

        cursor.execute(
            # f"SELECT * FROM {app_name}_{model_name} ORDER BY id DESC LIMIT 10"
            f"SELECT * FROM {model_name} ORDER BY id DESC LIMIT 10"
        )
        recent_records = cursor.fetchall()
        recent_records = [list(record) for record in recent_records]
        recent_records = json.dumps(recent_records, indent=2, default=datetime_handler)

    return render(
        request,
        "dogfoot/recent_records.html",
        {
            "app_name": app_name,
            "model_name": model_name,
            "app_names": app_names,
            "table_columns": table_columns,
            "recent_records": recent_records,
        },
    )


from django.db import connection


def get_db_schema(request):
    """
    Get the database schema.

    Parameters:
    - request: The incoming HTTP request.

    Returns:
    - A rendered HTML page with the database schema.
    """

    with connection.cursor() as cursor:
        all_table_names = connection.introspection.table_names()
        table_columns = {
            table: connection.introspection.get_table_description(cursor, table)
            for table in all_table_names
        }
        table_foreign_keys = {
            table: {
                name: details
                for name, details in connection.introspection.get_constraints(
                    cursor, table
                ).items()
                if details["foreign_key"]
            }
            for table in all_table_names
        }

    return render(
        request,
        "dogfoot/db_schema.html",
        {
            "table_columns": table_columns,
            "table_foreign_keys": table_foreign_keys,
        },
    )

templates/dogfoot/_dashboard_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <title>{% block title %}Dogfoot {% endblock title %}</title>
    <meta name="description" content="A framework for launching new Django projects quickly.">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <script src="https://unpkg.com/@popperjs/core@2"></script>

    {% block css %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css">

    {% endblock css %}

    {$ block custom_css %}

    {$ block custom_css %}


</head>

<body>
    <div class="container-fluid">
        <header class="p-3 mb-3 border-bottom ">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/"
                    class="d-flex align-items-center justify-content-start mb-2 mb-lg-0 link-body-emphasis text-decoration-none"
                    style="margin-right: 4rem;">

                    <h4>Dogfoot</h4>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'dogfoot:home' %}" class="nav-link px-2 link-secondary">Overview</a></li>
                    <li><a href="{% url 'dogfoot:get-db-schema' %}" class="nav-link px-2 link-secondary">DB Schema</a>
                    </li>

                </ul>


                <div class="dropdown text-end">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Hello
                        {{ user.username }}</a>
                    </a>
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url 'accounts:user-profile' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:user-update' %}">Basic user information</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a></li>
                    </ul>
                </div>
            </div>
        </header>
    </div>

    <div class="container-fluid d-flex flex-column text-start gap-3 min-vh-100">
        <div class="row">
            <div class="col-md-2">


                <ul class="list-unstyled ps-0">
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                            data-bs-target="#home-collapse" aria-expanded="true">
                            Database
                        </button>
                        <div class="collapse show" id="home-collapse">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                <li><a href="/dogfoot/all" class="link-dark rounded">Tables</a>
                                </li>
                                <li><a href="#" class="link-dark rounded">New case</a></li>

                            </ul>
                        </div>
                    </li>
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                            data-bs-target="#dashboard-collapse" aria-expanded="false">
                            Dashboard
                        </button>
                        <div class="collapse" id="dashboard-collapse">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                <li><a href="#" class="link-dark rounded">Overview</a></li>
                                <li><a href="#" class="link-dark rounded">Weekly</a></li>
                                <li><a href="#" class="link-dark rounded">Monthly</a></li>
                                <li><a href="#" class="link-dark rounded">Annually</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                            data-bs-target="#orders-collapse" aria-expanded="false">
                            Orders
                        </button>
                        <div class="collapse" id="orders-collapse">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                <li><a href="#" class="link-dark rounded">New</a></li>
                                <li><a href="#" class="link-dark rounded">Processed</a></li>
                                <li><a href="#" class="link-dark rounded">Shipped</a></li>
                                <li><a href="#" class="link-dark rounded">Returned</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="border-top my-3"></li>
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                            data-bs-target="#account-collapse" aria-expanded="false">
                            Account
                        </button>
                        <div class="collapse" id="account-collapse">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">

                                <li><a href="#" class="link-dark rounded">New...</a></li>
                                <li><a href="#" class="link-dark rounded">Profile</a></li>
                                <li><a href="#" class="link-dark rounded">Settings</a></li>
                                <li><a href="{% url 'account_logout' %}" class="link-dark rounded">Log out</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>

            <div class="col-md-10 border-start">

                {% block content %}

                {% endblock content %}


            </div>
        </div>


    </div>
    <footer class="py-3 my-4" style="border-top:1px solid;">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
        </ul>
        <p class="text-center text-body-secondary">© 2023 Company, Inc</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.js"
        integrity="sha384-eI7PSr3L1XLISH8JdDII5YN/njoSsxfbrkCTnJrzXt+ENP5MOVBxD+l6sEG4zoLp"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <!-- and it's easy to individually load additional languages -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/python.min.js"></script>
    <script>hljs.highlightAll();</script>
    {% block custom_js %}

    {% endblock custom_js %}
</body>

</html>

templates/dogfoot/db_schema.html
{% extends "dogfoot/dogfoot_base.html" %}

{% load dogfoot_filters %}

{% block title %}Intraoral Cases{% endblock %}

{% block content %}

{% for table, columns in table_columns.items %}
<h2>{{ table }}</h2>
<h3>Columns</h3>
<ul>
    {% for column in columns %}
    <li>{{ column.name }} ({{ column.type_code }})</li>
    {% endfor %}
</ul>
<h3>Foreign Keys</h3>
<ul>
    {% for fk_name, fk_details in table_foreign_keys.table.items %}
    <li>{{ fk_name }} -> {{ fk_details.foreign_key }}</li>
    {% endfor %}
</ul>
{% endfor %}
{% endblock %}

"table_columns": table_columns,
"table_foreign_keys": table_foreign_keys,

templates/dogfoot/dj_code_generate.html
{% extends "dogfoot/dogfoot_base.html" %}

{% load dogfoot_filters %}

{% block title %}Intraoral Cases{% endblock %}

{% block content %}

<div class="h2 p-4">
    Current app: {{ app_name }}
</div>
<div class="p-4">
    <a class="btn btn-success" href="/dogfoot/table/all">All</a>
    {% for app_name in app_names %}

    <a class="btn btn-success" href="/dogfoot/table/{{app_name}}"> {{ app_name }}</a>

    {% endfor %}

</div>
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-2 p-4">
    {% for table, columns in table_columns.items %}
    <div class="col">
        <div class="card" style="width:18rem;">
            <div class="card-header bg-dark h6 text-light ">
                {{ table }}
            </div>
            <div class="card-body">
                <p class="card-text">
                <ul class="list-group list-group-flush">
                    {% for column in columns %}
                    <li class="d-flex justify-content-between">
                        <span style="font-size:14px;font-weight: bold;margin-left:1rem;">{{ column.name }}</span>
                        <span style="font-size:14px;margin-right:1rem">{{ column.type_code }}</span>
                    </li>
                    {% endfor %}
                </ul>
                </p>
                <hr>
                <a href="/dogfoot/table/{{table|get_app_name}}/{{table}}/generate"
                    class="btn btn-success btn-sm">Generate</a>
                <a href="/dogfoot/table/{{table|get_app_name}}/{{table}}/get_recent_records"
                    class="btn btn-success btn-sm">
                    Get records
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="d-flex flex-column flex-wrap p-2">
    <div class="card" style="margin-left:1rem; margin-bottom:1rem;">
        <div class="card-header bg-dark h5 text-light ">
            urls.py
        </div>
        <pre><code>{{ code_gen.urls_gen|safe }}</code></pre>
    </div>
    <div class="card" style="margin-left:1rem; margin-bottom:1rem;">
        <div class="card-header bg-dark h5 text-light ">
            views.py
        </div>
        <pre><code>{{ code_gen.views_gen|safe }}</code></pre>
    </div>
    <div class="card" style="margin-left:1rem; margin-bottom:1rem;">
        <div class="card-header bg-dark h5 text-light ">
            forms.py
        </div>
        <pre><code>{{ code_gen.forms_gen|safe }}</code></pre>
    </div>
    <div class="card" style="margin-left:1rem; margin-bottom:1rem;">
        <div class="card-header bg-dark h5 text-light ">
            ~.html
        </div>
        <pre><code>{{ code_gen.html_gen|safe }}</code></pre>
    </div>


</div>


{% endblock content %}

templates/dogfoot/dogfoot_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <title>{% block title %}Dogfoot {% endblock title %}</title>
    <meta name="description" content="A framework for launching new Django projects quickly.">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <script src="https://unpkg.com/@popperjs/core@2"></script>

    {% block css %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css">

    {% endblock %}


</head>

<body>
    <div class="container-fluid">
        <header class="p-3 mb-3 border-bottom ">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/"
                    class="d-flex align-items-center justify-content-start mb-2 mb-lg-0 link-body-emphasis text-decoration-none"
                    style="margin-right: 4rem;">

                    <h4>Dogfoot</h4>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'dogfoot:home' %}" class="nav-link px-2 link-secondary">Overview</a></li>
                    <li><a href="{% url 'dogfoot:get-db-schema' %}" class="nav-link px-2 link-secondary">DB Schema</a>
                    </li>

                </ul>


                <div class="dropdown text-end">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Hello
                        {{ user.username }}</a>
                    </a>
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url 'accounts:user-profile' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:user-update' %}">Basic user information</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a></li>
                    </ul>
                </div>
            </div>
        </header>
    </div>

    <div class="container-fluid d-flex flex-column text-start gap-3 min-vh-100">
        <div class="row">
            <div class="col-md-2">


                <ul class="list-unstyled ps-0">
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                            data-bs-target="#home-collapse" aria-expanded="true">
                            Database
                        </button>
                        <div class="collapse show" id="home-collapse">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                <li><a href="/dogfoot/all" class="link-dark rounded">Tables</a>
                                </li>
                                <li><a href="#" class="link-dark rounded">New case</a></li>

                            </ul>
                        </div>
                    </li>
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                            data-bs-target="#dashboard-collapse" aria-expanded="false">
                            Dashboard
                        </button>
                        <div class="collapse" id="dashboard-collapse">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                <li><a href="#" class="link-dark rounded">Overview</a></li>
                                <li><a href="#" class="link-dark rounded">Weekly</a></li>
                                <li><a href="#" class="link-dark rounded">Monthly</a></li>
                                <li><a href="#" class="link-dark rounded">Annually</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                            data-bs-target="#orders-collapse" aria-expanded="false">
                            Orders
                        </button>
                        <div class="collapse" id="orders-collapse">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                <li><a href="#" class="link-dark rounded">New</a></li>
                                <li><a href="#" class="link-dark rounded">Processed</a></li>
                                <li><a href="#" class="link-dark rounded">Shipped</a></li>
                                <li><a href="#" class="link-dark rounded">Returned</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="border-top my-3"></li>
                    <li class="mb-1">
                        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse"
                            data-bs-target="#account-collapse" aria-expanded="false">
                            Account
                        </button>
                        <div class="collapse" id="account-collapse">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">

                                <li><a href="#" class="link-dark rounded">New...</a></li>
                                <li><a href="#" class="link-dark rounded">Profile</a></li>
                                <li><a href="#" class="link-dark rounded">Settings</a></li>
                                <li><a href="{% url 'account_logout' %}" class="link-dark rounded">Log out</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>

            <div class="col-md-10 border-start">

                {% block content %}

                {% endblock content %}


            </div>
        </div>


    </div>
    <footer class="py-3 my-4" style="border-top:1px solid;">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
        </ul>
        <p class="text-center text-body-secondary">© 2023 Company, Inc</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.js"
        integrity="sha384-eI7PSr3L1XLISH8JdDII5YN/njoSsxfbrkCTnJrzXt+ENP5MOVBxD+l6sEG4zoLp"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <!-- and it's easy to individually load additional languages -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/python.min.js"></script>
    <script>hljs.highlightAll();</script>
</body>

</html>

templates/dogfoot/index.html
{% extends "dogfoot/dogfoot_base.html" %}
{% block title %}Dog Foot Management Center{% endblock %}

{% block content %}

<div class="h2 p-4">
    Current app: {{ app_name }}
</div>
<div class="p-4">
    <a class="btn btn-success" href="/dogfoot/table/all">All</a>
    {% for app_name in app_names %}

    <a class="btn btn-success" href="/dogfoot/table/{{app_name}}"> {{ app_name }}</a>

    {% endfor %}

</div>

{% endblock content %}

templates/dogfoot/table.html
{% extends "dogfoot/dogfoot_base.html" %}

{% load dogfoot_filters %}

{% block title %}Intraoral Cases{% endblock %}

{% block content %}

<div class="h2 p-4">
    Current app: {{ app_name }}
</div>
<div class="p-4">
    <a class="btn btn-success" href="/dogfoot/table/all">All</a>
    {% for app_name in app_names %}

    <a class="btn btn-success" href="/dogfoot/table/{{app_name}}"> {{ app_name }}</a>

    {% endfor %}

</div>

<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-2 p-4">
    {% for table, columns in table_columns.items %}
    <div class="col">
        <div class="card">
            <div class="card-header bg-dark h6 text-light ">
                {{ table }}
            </div>
            <div class="card-body">
                <p class="card-text">
                <ul class="list-group list-group-flush">
                    {% for column in columns %}
                    <li class="d-flex justify-content-between">
                        <span style="font-size:14px;font-weight: bold;margin-left:1rem;">{{ column.name }}</span>
                        <span style="font-size:14px;margin-right:1rem">{{ column.type_code }}</span>
                    </li>
                    {% endfor %}
                </ul>
                </p>

                <hr>
                <a href="/dogfoot/table/{{table|get_app_name}}/{{table}}/generate"
                    class="btn btn-success btn-sm">Generate</a>
                <a href="/dogfoot/table/{{table|get_app_name}}/{{table}}/get_recent_records"
                    class="btn btn-success btn-sm">
                    Get records
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock content %}